global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          instance: 'db-server'

  #  альтернатива  
  # - job_name: 'netdata'
  #   metrics_path: '/api/v1/allmetrics'
  #   params:
  #     format: ['prometheus']
  #   static_configs:
  #     - targets: ['localhost:19999']
