---
- name: Copy backup script
  template:
    src: db_backup.sh.j2
    dest: "{{ backup_script_path }}/db_backup.sh"
    owner: root
    group: root
    mode: '0750'

- name: Copy configuration file
  template:
    src: config.env.j2
    dest: "{{ backup_script_path }}/config.env"
    owner: root
    group: root
    mode: '0600'
  no_log: true
